export const students =  [
    {
        barkod: 1910399,
        name: 'Айя',
        surname: 'Мырзабаева',
        age: 21,
        gpa: 8,
        gender: 'жен',
        course: '4',
    },
    {
        barkod: 1910374,
        name: 'Амина',
        surname: 'Толеухан',
        age: 19,
        gpa: 10,
        gender: 'жен',
        course: '4',
    },
    {
        barkod: 1910466,
        name: 'Досжан',
        surname: 'Байтолла',
        age: 20,
        gpa: 10,
        gender: 'муж',
        course: '4',
    },
    {
        barkod: 1910458,
        name: 'Канат',
        surname: 'Амангельдиев',
        age: 21,
        gpa: 7,
        gender: 'муж',
        course: '4',
    },
    {
        barkod: 1910889,
        name: 'Айнаш',
        surname: 'Абильдинова',
        age: 20,
        gpa: 8,
        gender: 'жен',
        course: '4',
    },
    {
        barkod: 1910477,
        name: 'Нурмахан',
        surname: 'Жайлау',
        age: 20,
        gpa: 4,
        gender: 'муж',
        course: '4',
    },
    {
        barkod: 1910255,
        name: 'Дильназ',
        surname: 'Нариманова',
        age: 20,
        gpa: 6,
        gender: 'жен',
        course: '4',
    },
    {
        barkod: 1910233,
        name: 'Алина',
        surname: 'Орынбасар',
        age: 21,
        gpa: 6,
        gender: 'жен',
        course: '4',
    },
    {
        barkod: 1916684,
        name: 'Гульсанам',
        surname: 'Салимова',
        age: 21,
        gpa: 3,
        gender: 'жен',
        course: '4',
    },
    {
        barkod: 1916684,
        name: 'Гульдана',
        surname: 'Бердалиева',
        age: 21,
        gpa: 3,
        gender: 'жен',
        course: '4',
    },
    {
        barkod: 1916684,
        name: 'Алибек',
        surname: 'Бегалиев',
        age: 21,
        gpa: 3,
        gender: 'муж',
        course: '4',
    },
    {
        barkod: 1916684,
        name: 'Бекарыс',
        surname: 'Туякбай',
        age: 21,
        gpa: 3,
        gender: 'муж',
        course: '4',
    }
]